title: LCP Server
description: Documentation for the Readium LCP Server
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Just the Docs configuration
search_enabled: true
heading_anchors: true
